apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-web
  template:
    metadata:
      labels:
        app: django-web
    spec:
      containers:
        - name: django-web
          image: gireeshkumar1723/docker-web:latest
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: django-web-config
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: django-web-config
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-web-config
                  key: ALLOWED_HOSTS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: django-db-secret
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: django-db-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-db-secret
                  key: MYSQL_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: django-web-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: django-web-config
                  key: DB_PORT

