apiVersion: v1
kind: Secret
metadata:
  name: django-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: ecommerce_db
  MYSQL_USER: ecommerce_user
  MYSQL_PASSWORD: root
  DB_PASSWORD: root

