apiVersion: v1
kind: ConfigMap
metadata:
  name: django-web-config
data:
  SECRET_KEY: your_secret_key_here
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  DB_NAME: ecommerce_db
  DB_USER: ecommerce_user
  DB_HOST: django-db
  DB_PORT: "3306"

