apiVersion: v1
kind: Service
metadata:
  name: django-web-service
spec:
  selector:
    app: django-web   # must match Deployment label
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort      # use LoadBalancer if deploying to cloud

